### PR TITLE
fix: name all contributions the same way

### PR DESCRIPTION
**Pull request by vmx**
Some contributions haven't had the `_raw` suffix, which would make
verification of the signature harder.

I don't know if it's the right thing to do, please carefully review and make
sure it's not a stupid thing to do.

### CODE REVIEW

**Comment by vmx** [comment]
Let's take `sdr_poseidon_32gib_b288702_1_small` as an example.

On the S3 bucket at https://trusted-setup.s3.amazonaws.com/phase2-mainnet there currently are no `.contrib.sig` files AFAICT. Though there are `.contrib` files. Though in this case there is only `sdr_poseidon_32gib_b288702_1_small_raw.contrib` available, the **raw** version, there is **no** non-raw version. This means that we cannot verify the signature, unless we use the signature from the non-raw version.

Moving forward I can see two ways:

 - We don't verify signatures of contributions that used the non-raw format.
 - We also checkout the non-raw version of the contributions and check against those. Though this is a bit awkward as we use the raw version of the parameters for the actual verification.

To me the core question is still: is a `.contrib` file identical for raw and non-raw or not?

**Comment by porcuquine** [comment]
I understand your question now. I cannot answer with 100% certainty without more digging. Can you confirm that making the change you propose actually works? If it does, it is likely to be safe — so please let me know: that will help me investigate.

**Comment by vmx** [comment]
I haven't tried it yet as I don't have all the public keys. If I would have especially from those files this PR renames, I can try.

**Comment by vmx** [comment]
I just converted a raw file to a non-raw file. The last 544 bytes (that's what is then b2sum'ed and goes into the .contrib file) are identical. I would frame the .contrib file as "the b2sum of the last 544 bytes of the parameters you contributed to". It doesn't matter if it's raw on non-raw format, you can round-trip then.

So I think we should do the renaming to make things less confusing for people who want to verify things. The current verification script is only using raw versions, so it would be confusing to see non-raw .contrib files.

**Comment by porcuquine** [comment]
Yes, I believe it's okay.

**Comment by vmx** [comment]
I'd also like to mention that the `raw`<-> `non-raw` conversion works in both ways. So if somone signed the `non-raw` contribution, but we publish it as a seemingly `raw` contribution that is fine. You can always convert the files and the contribution will stay the same. So essentially the same bytes are going to be signed, whether you use `raw` or `non-raw`.

**Pull request merged**
