### PR TITLE
Ensure initial params used are large.

### PR DESCRIPTION
**Pull request by porcuquine**
We should never download small params for the 'zeroth contribution', and if any are present we should delete them. Otherwise, they will be used when verifying the first contribution. We don't want this to happen. Instead we want verification to fall back to using the large parameters we generated locally so a verifier can observe the relationship between the deterministically-generated initial params and the chain of following contributions.

### CODE REVIEW

**Review by ribasushi — APPROVED** [review]

**Comment by vmx** [comment]
@porcuquine Instead of a code review I decided I just make the change I'd have commented on (for quicker turnaround times). Please indicate if you agree with that change.

**Comment by vmx** [comment]
@porcuquine nevermind. I've a new PR soon, which supersedes this one.

**Comment by vmx** [comment]
Superseded by https://github.com/filecoin-project/phase2-attestations/pull/25, hence closing this one.

**Comment by porcuquine** [comment]
@vmx (cc:@ribasushi) The code you proposed to remove here was important. The underlying verification will first look for small raw parameters. If it doesn't find them, it will look for small non-raw parameters. If it doesn't find those either, it will fall back to large. We need it to use the large parameters. Therefore, we need to positively ensure that neither small raw nor small non-raw parameters exist. Otherwise, they will be used instead of the large ones that were generated locally.

**Comment by ribasushi** [comment]
Agree with @porcuquine , it's sensible to be thorough.

**Comment by vmx** [comment]
@porcuquine with the current script, they won't get the wrong parameter files from anywhere. I don't want to complicate scripts for the case when people do not follow instructions and do random things.

Though if you really want that, we can add it on top of #25 once merged.

**Pull request closed without merging**
